export const BlogPostData = [
  {
    id: 1,
    source: "/images/protection-img.jpeg",
    date: "03",
    month: "Oct",
    linkto: "/blog/navigation-data-privacy-regulation",
    title: "Navigating Data Privacy Regulations: A Guide to GDPR Compliance in IT Systems",
    des: "In today's digital age, data privacy has become a paramount concern for individuals and organizations alike. The General Data Protection Regulation (GDPR), implemented in May 2018, has significantly reshaped",
  },
  {
    id: 2,
    source: "/images/mobile-5g.png",
    date: "22",
    month: "Sep",
    linkto: "/blog/impact-of-5g-on-mobile-development",
    title: "The Impact of 5G on Mobile App Development",
    des: "In today's fast-paced digital world, mobile app development is continually evolving to keep up with the latest technological advancements. One such game-changing innovation is the rollout of 5G networks.",
  },
  {
    id: 3,
    source: "/images/chatgpt.png",
    date: "12",
    month: "Sep",
    linkto: "/blog/chatgpt-vs-googlebrad",
    title: "ChatGPT AI vs. Google’s Brad AI",
    des: "Google is known for a wide range of products and services, including its search engine,       Android operating system, Google Maps, Gmail, Google Drive, and many others. However, I don't have information",
  },
  {
    id: 4,
    source: "/images/blockchain.png",
    date: "28",
    month: "Aug",
    linkto: "/blog/blockchain-beyond-cryptocurrency",
    title: "Blockchain Beyond Cryptocurrency",
    des: "Blockchain technology, originally designed to underpin cryptocurrencies like Bitcoin, has evolved into a versatile tool with applications across a myriad of industries. Its unique features, such as",
  },
  {
    id: 5,
    source: "/images/role-of-ai.jpg",
    date: "14",
    month: "Aug",
    linkto: "/blog/role-of-ai-in-e-commerce",
    title: "Role of AI in e-commerce.",
    des: "In today’s digital era, e-commerce has become an integral part of our daily routines. whether it’s buying groceries or selecting birthday presents, we rely heavily on the Internet for our shopping needs.",
  },
  {
    id: 6,
    source: "/images/blog.jpg",
    date: "18",
    month: "July",
    linkto: "/blog/web-design-development-and-services",
    title:
      "Web Design, Development, and Services: What Is It? How Does It Impact Your Life? Everyone Needs To Know This! ",
    des: "If you want to grow your business, it's important to have an online presence. But what does that mean? It means that you need a website.",
  },
  {
    id: 7,
    source: "/images/blog1.png",
    date: "11",
    month: "July",
    linkto: "/blog/choosing-a-web-development-company",
    title: "Choosing A Web Development Company Is Easier Than You Think",
    des: "Using the skill of a top-quality web development company can change your business and make it even more successful.",
  },
];
