export const portfolioData = {
  web: [
    {
      title: "E-Commerce Platform",
      description:
        "Collaborative project management tool with real-time updates, team collaboration, and advanced analytics.",
      tech: ["Next.js", "TypeScript", "Stripe", "PostgreSQL"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Full Stack",
    },
    {
      title: "Task Management Dashboard",
      description:
        "Collaborative project management tool with real-time updates, team collaboration, and advanced analytics.",
      tech: ["React", "Node.js", "Socket.io", "MongoDB"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Web App",
    },
    {
      title: "Real Estate Website",
      description: "Modern real estate platform with property listings, virtual tours, and mortgage calculator.",
      tech: ["Vue.js", "Laravel", "MySQL", "Tailwind CSS"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Website",
    },

  ],
  mobile: [
    {
      title: "Fitness Tracking App",
      description: "Cross-platform mobile app for workout tracking, nutrition logging, and progress visualization.",
      tech: ["React Native", "Firebase", "Redux", "Expo"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Health & Fitness",
    },
    {
      title: "Food Delivery App",
      description: "On-demand food delivery application with real-time tracking and payment integration.",
      tech: ["Flutter", "Node.js", "MongoDB", "Stripe"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Delivery",
    },
    {
      title: "Social Media App",
      description: "Instagram-like social platform with photo sharing, stories, and real-time messaging.",
      tech: ["React Native", "GraphQL", "PostgreSQL", "AWS S3"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Social",
    },
  ],
  design: [
    {
      title: "Banking App UI/UX",
      description:
        "Complete mobile banking application design with user research, wireframes, and interactive prototypes.",
      tech: ["Figma", "Adobe XD", "Principle", "InVision"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Mobile Design",
    },
    {
      title: "SaaS Dashboard Design",
      description: "Modern dashboard design for analytics platform with data visualization and responsive layouts.",
      tech: ["Figma", "Adobe Illustrator", "Sketch", "Zeplin"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Web Design",
    },
    {
      title: "E-commerce Redesign",
      description: "Complete redesign of online store with improved user experience and conversion optimization.",
      tech: ["Figma", "Adobe Photoshop", "Hotjar"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "UX Design",
    },
  ],
  other: [
    {
      title: "Chrome Extension",
      description: "Productivity browser extension for time tracking and website blocking with detailed analytics.",
      tech: ["JavaScript", "Chrome APIs", "Local Storage", "CSS3"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Browser Extension",
    },
    {
      title: "Desktop Application",
      description: "Cross-platform desktop app for file management and organization with cloud sync capabilities.",
      tech: ["Electron", "React", "Node.js", "SQLite"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Desktop App",
    },
    {
      title: "API Development",
      description: "RESTful API service for multi-tenant SaaS application with authentication and rate limiting.",
      tech: ["Node.js", "Express", "JWT", "Redis"],
      image: "/placeholder.svg?height=250&width=400",
      liveLink: "#",
      githubLink: "#",
      category: "Backend",
    },
  ],
}